version: 2
updates:
  - package-ecosystem: terraform
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
  - package-ecosystem: gomod
    directory: lambda
    schedule:
      interval: daily
    cooldown:
      default-days: 1
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
